-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    city TEXT,
    school TEXT,
    mobile TEXT, -- Added mobile number
    password TEXT, -- Note: In a real app, use Supabase Auth. This is for the demo to match Dexie.
    "totalPoints" INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Readings Table
CREATE TABLE IF NOT EXISTS readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bookId" TEXT NOT NULL,
    "userId" TEXT NOT NULL REFERENCES users(id),
    "startTime" BIGINT NOT NULL,
    "endTime" BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) - Optional for now but good practice
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE readings ENABLE ROW LEVEL SECURITY;

-- Create Policies (Public access for this demo to match local-first nature without complex auth)
CREATE POLICY "Public users access" ON users FOR ALL USING (true);
CREATE POLICY "Public readings access" ON readings FOR ALL USING (true);
